# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Krzysztof Miąsko
email: kmiasko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Krzysztof Miąsko - Frontend | Backend developer. Nowoczesne strony WWW, aplikacje internetowe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kmiasko.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules/bourbon/app/assets/stylesheets
    - node_modules/bourbon-neat/app/assets/stylesheets

collections:
  - portfolios

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
